version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      frontend-minor-patch:
        update-types: ["minor", "patch"]
    open-pull-requests-limit: 10

  - package-ecosystem: "cargo"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      backend-minor-patch:
        update-types: ["minor", "patch"]
    open-pull-requests-limit: 10

  - package-ecosystem: "cargo"
    directory: "/crates/sely-game-core"
    schedule:
      interval: "weekly"
    groups:
      wasm-minor-patch:
        update-types: ["minor", "patch"]
    open-pull-requests-limit: 5

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
    open-pull-requests-limit: 5
