import { ArrowLeft, ExternalLink, ShieldCheck } from "lucide-react";
import { Link } from "wouter";
import { publicContactEmail } from "@/lib/contact";
import type { SiteLocale } from "@/lib/i18n";

type LegalPageProps = { kind: "privacy" | "terms" | "accessibility"; locale?: SiteLocale };

const Contact = () => <a href={`mailto:${publicContactEmail}`}>{publicContactEmail}</a>;

export default function Legal({ kind, locale = "tr" }: LegalPageProps) {
  const privacy = kind === "privacy";
  const accessibility = kind === "accessibility";
  const english = locale === "en";
  const title = privacy ? (english ? "Privacy & KVKK Notice" : "KVKK Gizlilik Politikası") : accessibility ? (english ? "Accessibility Statement" : "Erişilebilirlik Bildirimi") : (english ? "Terms of Use" : "Kullanım Koşulları");
  return <main className="legal-page">
    <header className="legal-nav"><Link href={english ? "/en" : "/"} className="back-button"><ArrowLeft size={18} /> {english ? "Game catalogue" : "Oyun kataloğu"}</Link><span>SELY.TR · {english ? "INFORMATION & RIGHTS" : "BİLGİLER VE HAKLAR"}</span></header>
    <article className="legal-article">
      <div className="legal-heading"><span className="studio-kicker">{accessibility ? (english ? "ACCESSIBILITY · CONTINUOUS IMPROVEMENT" : "ERİŞİLEBİLİRLİK · SÜREKLİ İYİLEŞTİRME") : (english ? "DRAFT · LEGAL REVIEW REQUIRED" : "TASLAK · HUKUKİ GÖZDEN GEÇİRME GEREKİR")}</span><h1>{title}</h1><p>{english ? "Last updated: 25 August 2026" : "Son güncelleme: 25 Ağustos 2026"}</p></div>
      {english ? <EnglishLegalContent kind={kind} /> : privacy ? <PrivacyContent /> : accessibility ? <AccessibilityContent /> : <TermsContent />}
      <section className="legal-note"><ShieldCheck size={21} /><p>{english ? <>For questions or feedback, use <Contact />. This public source-available distribution deliberately uses a placeholder address; the production copy must publish the actual responsible contact channel.</> : accessibility ? <>Erişilebilirlik sorunu veya önerisi bildirmek için <Contact /> adresini kullanabilirsiniz. Public dağıtımda bu adres placeholder’dır; prod kopyasında gerçek destek kanalı eklenmelidir.</> : <>Bu public kaynak görünür dağıtımda iletişim bilgisi bilinçli olarak placeholder’dır. Prod kopyasında gerçek veri sorumlusu ve başvuru kanalı, yayına almadan önce eklenmelidir.</>}</p></section>
    </article>
  </main>;
}

function EnglishLegalContent({ kind }: { kind: LegalPageProps["kind"] }) {
  if (kind === "accessibility") return <div className="legal-copy"><section><h2>1. Our approach</h2><p>SELY.TR MiniGame Hub aims to make its short game experiences usable by as many people as possible. Accessibility is considered in interface and control choices; this statement describes the current approach and is not a formal conformance certificate.</p></section><section><h2>2. Available features</h2><p>Catalogue, game-start and information links use meaningful labels. Core flows provide visible buttons, keyboard focus and touch alternatives. Direction-based games support arrow-key input and large touch controls. Status, objectives and feedback are presented with text in addition to colour.</p></section><section><h2>3. Preferences and limitations</h2><p>The interface limits non-essential movement when a reduced-motion preference is set. Some games use timing, marking or spatial decisions and may not provide an equivalent experience for every assistive technology or motor need. Sound is not required to complete a game.</p></section><section><h2>4. Feedback</h2><p>Please send the device, browser, affected game and a short description of any barrier to <Contact />.</p></section></div>;
  if (kind === "privacy") return <div className="legal-copy"><section><h2>1. Purpose and controller</h2><p>This notice describes how SELY.TR MiniGame Hub handles personal data. The public GitHub version uses <Contact /> as a placeholder; production must replace it with the actual controller and request channel.</p></section><section><h2>2. Data minimisation</h2><p>Core games do not require an account. Best scores and preferences are stored locally in the browser. Daily game packs contain non-personal date, game, seed, difficulty, ruleset and validation fields.</p></section><section><h2>3. Storage and rights</h2><p>Daily packs may be retained for up to 90 days and limited security logs for up to 14 days. The Turkish production version must provide the complete KVKK disclosure and request process.</p></section></div>;
  return <div className="legal-copy"><section><h2>1. Scope</h2><p>These terms apply to the SELY.TR MiniGame Hub catalogue and daily content. Game rules, scoring and daily editions may change as the project evolves.</p></section><section><h2>2. Acceptable use</h2><p>Do not overload the service, automate abusive requests, bypass safeguards or remove ownership notices. Daily-content endpoints exist only for reasonable game-client use.</p></section><section><h2>3. Source availability and intellectual property</h2><p>The public repository is source-available, not open source. Except for the limited evaluation permission in the repository’s SELY Proprietary Source-Available License, you may not copy, modify, distribute, host, sublicense or create derivative works from the code, game logic, visual assets or marks. The service is provided as is and may be unavailable because of hosting, network or database interruptions.</p></section></div>;
}

function AccessibilityContent() {
  return <div className="legal-copy">
    <section><h2>1. Yaklaşımımız</h2><p>SELY.TR MiniGame Hub’ın herkes için kullanılabilir olmasını hedefliyoruz. Oyunlar kısa, açık kurallı deneyimler olarak tasarlanır; erişilebilirlik, sonradan eklenen bir katman değil, arayüz ve oyun kontrolü kararlarının parçasıdır. Bu bildirim bir resmî uygunluk sertifikası değildir; mevcut durumumuzu ve geliştirme niyetimizi açıklar.</p></section>
    <section><h2>2. Kullanılabilir özellikler</h2><p>Katalog, oyun başlatma ve hukukî bilgi bağlantıları anlamlı metinlerle etiketlenir. Temel oyun akışlarında görünür düğmeler, klavye odakları ve dokunmatik alternatifler bulunur. Yön temelli oyunlar klavye yön tuşlarıyla da oynanabilir; dokunmatik cihazlarda büyük hareket denetimleri sağlanır. Renk, bilgi aktarmanın tek yolu olarak kullanılmamaya çalışılır; skor, hedef, geri bildirim ve tur durumu metinle de gösterilir.</p></section>
    <section><h2>3. Hareket ve görsel tercihler</h2><p>Arayüz, işletim sistemi veya tarayıcıda azaltılmış hareket tercihi seçildiğinde gereksiz geçişleri sınırlayacak şekilde tasarlanır. Kontrast, odak halkaları ve okunabilir tipografi düzenli olarak gözden geçirilir. Oyunlardaki güçlü görsel efektlerin gerekli olduğu yerlerde, oyunun durumu metin ve kontrol ipuçlarıyla da açıklanır.</p></section>
    <section><h2>4. Bilinen sınırlamalar</h2><p>Bazı oyunlar zamanlama, işaretleme veya konumsal karar gerektirir; bu nedenle her oyun her yardımcı teknoloji veya motor beceri ihtiyacı için aynı derecede uygun olmayabilir. Ses, oyunun tamamlanması için zorunlu değildir. Yeni içerik ve günlük bölümler eklendikçe, klavye erişimi, odak sırası, dokunmatik hedef boyutu ve metinsel geri bildirim ayrıca test edilir.</p></section>
    <section><h2>5. Geri bildirim ve talep</h2><p>Bir içerik veya kontrolün erişilemez olduğunu düşünüyorsanız; kullandığınız cihazı, tarayıcıyı, ilgili oyun/sayfayı ve mümkünse sorunun kısa açıklamasını <Contact /> adresine gönderebilirsiniz. Bildirimler önceliklendirilir; makul bir alternatif veya düzeltme değerlendirilir.</p></section>
  </div>;
}

function PrivacyContent() {
  return <div className="legal-copy">
    <section><h2>1. Amaç ve veri sorumlusu</h2><p>Bu metin, SELY.TR MiniGame Hub’ın kişisel verileri nasıl ele aldığını açıklamak için hazırlanmıştır. Public GitHub dağıtımında veri sorumlusu iletişimi <Contact /> olarak gösterilir; prod ortamında bu alan gerçek ticari unvan, adres ve başvuru kanalıyla değiştirilmelidir. Bu metin, 6698 sayılı Kişisel Verilerin Korunması Kanunu kapsamında aydınlatma amacı taşır.</p></section>
    <section><h2>2. İşlenen veriler ve veri minimizasyonu</h2><p>Uygulamanın ana oyunları hesap oluşturmayı gerektirmez. En iyi skorlar ve oyun tercihleri, varsayılan olarak cihazınızdaki yerel depolamada tutulur. Günlük bölüm üretim kayıtları tarih, oyun kimliği, deterministik tohum, zorluk, kural seti sürümü ve doğrulama özeti gibi kişisel veri içermeyen kısa parametrelerden oluşur. Sunucu güvenliği için barındırma sağlayıcısının tuttuğu sınırlı teknik erişim kayıtları oluşabilir.</p></section>
    <section><h2>3. İşleme amaçları ve hukuki sebep</h2><p>Teknik veriler hizmetin güvenli çalışması, hata ayıklama ve kötüye kullanımın önlenmesi için; yerel oyun tercihleri ise deneyimin hatırlanması için kullanılır. Oturum açma özelliği açıkça etkinleştirilirse, ilgili hesabın tanınması ve kullanıcı tercihinin eşlenmesi amacıyla sınırlı hesap bilgisi işlenebilir. Açık rıza gerektiren çerez, reklam kişiselleştirme veya pazarlama takibi bu sürümde kullanılmaz.</p></section>
    <section><h2>4. Aktarım, saklama ve imha</h2><p>Veriler, yalnız hizmeti barındıran altyapı ve seçilen veritabanı sağlayıcısında işlenebilir. Günlük oyun paketleri kişisel veri içermediği için 90 gün saklanır; daha eski paketler silinebilir veya yalnız istatistiksel değer kalacak biçimde anonimleştirilebilir. Güvenlik kayıtları, zorunlu daha uzun bir süre yoksa en fazla 14 gün saklanmalıdır. Hesap özelliği etkinleştirilirse saklama süresi, hesap amacı ortadan kalktığında veya silme talebi sonuçlandığında sona erer. Prod ortamındaki gerçek saklama süreleri bu metne eklenmelidir.</p></section>
    <section><h2>5. Çerezler ve yerel depolama</h2><p>Uygulama, oyun tercihlerini ve yerel skorları tarayıcı tarafında saklayabilir. Bu verileri tarayıcı ayarlarınızdan silebilirsiniz; silme işlemi cihazdaki ilerleme bilgisini kaldırır. Üçüncü taraf reklam çerezi veya davranışsal izleme kullanılmaz. Prod ortamında ayrıca analiz aracı eklenirse, bu politika ile çerez tercih mekanizması güncellenmelidir.</p></section>
    <section><h2>6. İlgili kişi hakları ve başvuru</h2><p>Kanun’un 11. maddesi uyarınca verilerinizin işlenip işlenmediğini öğrenme, bilgi talep etme, düzeltme, silme/yok etme ve zarar hâlinde tazminat talep etme haklarına sahip olabilirsiniz. Başvurularınızı prod ortamında ilan edilecek kanaldan; public dağıtım örneğinde ise <Contact /> üzerinden iletebilirsiniz. Başvurular, kimliğin doğrulanmasını gerektirebilir.</p></section>
    <section><h2>7. Kaynak ve güncelleme</h2><p>Bu taslak, KVKK’nın aydınlatma yükümlülüğü ve saklama/imha politikasına ilişkin resmî yayınları dikkate alınarak hazırlanmıştır. Gerçek veri akışı, sağlayıcı sözleşmeleri ve uluslararası aktarım durumu değişirse metin güncellenmelidir.</p><a className="source-link" href="https://www.kvkk.gov.tr/Icerik/5395/Aydinlatma-Yukumlulugunun-Yerine-Getirilmesi-Rehberi-Kurum-Internet-Sayfasinda-Yayinlanmistir-" target="_blank" rel="noreferrer">KVKK aydınlatma rehberi <ExternalLink size={14} /></a></section>
  </div>;
}

function TermsContent() {
  return <div className="legal-copy">
    <section><h2>1. Kapsam</h2><p>Bu koşullar, SELY.TR MiniGame Hub üzerinden sunulan oyun kataloğunu ve ilişkili günlük içerikleri kullanırken geçerlidir. Hizmete erişerek bu koşulları kabul etmiş sayılırsınız. Hizmetin belirli sürümleri deneysel olabilir; oyun kuralları, puanlama dengesi ve günlük bölüm yapısı değişebilir.</p></section>
    <section><h2>2. Kabul edilebilir kullanım</h2><p>Hizmeti hukuka aykırı amaçlarla kullanamaz, altyapıya aşırı yük bindiremez, otomatik isteklerle skor/erişim mekanizmalarını bozamaz, güvenlik önlemlerini aşmaya çalışamaz veya kaynak kodu/varlıklar üzerindeki telif bildirimlerini kaldıramazsınız. Günlük içerik API’si yalnız oyun istemcisinin makul kullanımına yöneliktir.</p></section>
    <section><h2>3. Fikri mülkiyet ve kaynak görünürlüğü</h2><p>Public repo kaynak erişimine açıktır; ancak açık kaynak değildir. Depodaki SELY Proprietary Source-Available License’ın sınırlı değerlendirme izni dışında kodun, oyun mantığının, görsel varlıkların veya marka işaretlerinin kopyalanması, değiştirilmesi, dağıtılması, barındırılması, alt lisanslanması ya da türev eser üretilmesi yasaktır. SELY adı, görsel kimliği ve oyun içerikleri ayrıca telif ve marka koruması altındadır.</p></section>
    <section><h2>4. Hizmetin kullanılabilirliği</h2><p>Hizmet "olduğu gibi" sunulur; kesintisiz, hatasız veya belirli bir cihazla uyumlu olacağı garanti edilmez. Günlük içerik üretimi, düşük kaynak tüketimi ve idempotent çalışma hedefiyle tasarlanır; buna rağmen barındırma, ağ veya üçüncü taraf veritabanı kesintileri yaşanabilir.</p></section>
    <section><h2>5. Değişiklikler ve iletişim</h2><p>Koşulların veya oyun içeriklerinin önemli ölçüde değişmesi hâlinde son güncelleme tarihi yenilenir. Public örnekte iletişim için <Contact /> kullanılır. Prod sürümünde gerçek işletmeci bilgisi ve başvuru yöntemi görünür biçimde eklenmelidir.</p></section>
    <section><h2>6. Uygulanacak hukuk</h2><p>Bu taslak Türkiye’de kullanıma yönelik hazırlanmıştır. Prod sürümünde işletmecinin merkez bilgisi ve yetkili mahkeme düzenlemesi, somut ticari yapı ve uygulanacak hukuka göre uzman incelemesiyle kesinleştirilmelidir.</p></section>
  </div>;
}
